file = open('logs.txt', 'r')
string = file.read()
string = string.replace(',', '\n')
string = string.replace('[', '')
string = string.replace(']', '')
string = string.replace('A', '')
string = string.replace('B', '')
file2 = open('input.txt', 'w')
file2.write(string)
file.close()
file2.close()