name: PokemonWebSpider
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Victor-PC\Victor <victordivi98@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  html: ^0.13.3+3
  http: ^0.12.0
  equatable: ^0.6.1
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
